const mongoose = require('mongoose');

/**
 * Payroll Model — Day 5 Full Implementation
 *
 * Stores the calculated payroll record for a staff member for a given month.
 * Payroll is generated by Admin; calculation is done server-side only.
 *
 * Formula:
 *   applicableSalary = min(basicSalary, MAX_APPLICABLE_SALARY=40000)
 *   dailySalary = applicableSalary / totalWorkingDays
 *   absenceDeduction = unauthorizedAbsentDays * dailySalary
 *   netSalary = applicableSalary - absenceDeduction
 */

const MAX_APPLICABLE_SALARY = 40000;

const payrollSchema = new mongoose.Schema(
  {
    // ── Employee Reference ──────────────────────────────────────────
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // ── Payroll Period ──────────────────────────────────────────────
    month: {
      type: Number, // 1–12
      required: true,
      min: 1,
      max: 12,
    },
    year: {
      type: Number,
      required: true,
      min: 2024,
    },

    // ── Salary Inputs ───────────────────────────────────────────────
    basicSalary: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    applicableSalary: {
      // min(basicSalary, 40000)
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },

    // ── Working Days Breakdown ──────────────────────────────────────
    totalWorkingDays: {
      // Calendar working days (excluding weeklyOffs + holidays)
      type: Number,
      default: 0,
    },
    presentDays: {
      type: Number,
      default: 0,
    },
    leaveDays: {
      // Approved leave days (no deduction)
      type: Number,
      default: 0,
    },
    absentDays: {
      // Unauthorized absences (cause deduction)
      type: Number,
      default: 0,
    },
    weeklyOffDays: {
      type: Number,
      default: 0,
    },
    holidayDays: {
      type: Number,
      default: 0,
    },

    // ── Calculation Results ─────────────────────────────────────────
    dailySalary: {
      // applicableSalary / totalWorkingDays
      type: Number,
      default: 0,
    },
    absenceDeduction: {
      // absentDays * dailySalary
      type: Number,
      default: 0,
    },

    // ── Extras (future extensibility) ──────────────────────────────
    allowances: {
      hra:     { type: Number, default: 0 },
      da:      { type: Number, default: 0 },
      ta:      { type: Number, default: 0 },
      medical: { type: Number, default: 0 },
      other:   { type: Number, default: 0 },
    },
    deductions: {
      pf:            { type: Number, default: 0 },
      pt:            { type: Number, default: 0 },
      tds:           { type: Number, default: 0 },
      loanRepayment: { type: Number, default: 0 },
      other:         { type: Number, default: 0 },
    },

    // ── Final Totals ────────────────────────────────────────────────
    grossSalary: {
      // applicableSalary + total allowances
      type: Number,
      default: 0,
    },
    netSalary: {
      // grossSalary - absenceDeduction - total deductions
      type: Number,
      default: 0,
    },

    // ── Status & Audit ──────────────────────────────────────────────
    status: {
      type: String,
      enum: ['Draft', 'Processed', 'Paid'],
      default: 'Draft',
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    paidAt: {
      type: Date,
      default: null,
    },
    remarks: {
      type: String,
      default: '',
      trim: true,
    },

    // ── Snapshot of holidays used in this calculation ───────────────
    holidays: {
      type: [Date],
      default: [],
    },
  },
  { timestamps: true }
);

// Prevent duplicate payroll per user per month per year
payrollSchema.index({ user: 1, month: 1, year: 1 }, { unique: true });

payrollSchema.statics.MAX_APPLICABLE_SALARY = MAX_APPLICABLE_SALARY;

module.exports = mongoose.model('Payroll', payrollSchema);
module.exports.MAX_APPLICABLE_SALARY = MAX_APPLICABLE_SALARY;
